services:
  postgres:
    image: postgres:17.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: salih-codes-dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "prowler-dev"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  adminer:
    image: adminer:5.2.1
    ports:
      - "8080:8080"
    environment:
      ADMINER_DESIGN: dark
      ADMINER_TITLE: Salih Codes Admin
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DEFAULT_USERNAME: postgres
      ADMINER_DEFAULT_PASSWORD: postgres

  maildev:
    image: maildev/maildev:2.2.1
    ports:
      - "1080:80"
      - "1025:25"

  # redis:
  #   image: redis/redis-stack:latest
  #   ports:
  #     - "6379:6379"
  #     - "8001:8001"
  #   environment:
  #     REDIS_PASSWORD: redis
  #   volumes:
  #     - redis_data:/var/lib/redis
  #   healthcheck:
  #     test:
  #       [
  #         "CMD",
  #         "redis-cli",
  #         "-h",
  #         "localhost",
  #         "-p",
  #         "6379",
  #         "-a",
  #         "redis",
  #         "ping",
  #       ]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 10s

volumes:
  postgres_data:
  redis_data:
